version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: weather_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./.docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE

  backend:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URI=$MONGO_URI
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules